### ISSUE TITLE
GoLang Scan Results No Showing in the UI

### ISSUE THREAD

**Issue by blxdaniel** [uartois/sonar-golang#17]
### Description

After running a scan on a go project, the UI does not show any results. However, the report.xml records the results

### Steps to Reproduce

1. Create a variable in a .go file that starts with k (i.e kNumberr)
2. run "sonar-scanner"
3. run "gometalinter.v1 --checkstyle > report.xml"
4. run "cat report.xml" 

### Content of your sonar-project.properties

sonar.projectKey=mygotest
sonar.projectName=My Go Test
sonar.projectVersion=1.0
sonar.golint.reportPath=report.xml //default
sonar.coverage.reportPath=coverage.xml // default
sonar.coverage.dtdVerification=false // if you want disabled the DTD verification for a proxy problem for example 
sonar.test.reportPath=test.xml //default
sonar.sources=./

### Log of sonar-scanner related to the plugin

10:57:41.521 INFO: Scanner configuration file: /Users/daniel/Downloads/sonar-scanner-3.0.3.778-macosx/conf/sonar-scanner.properties
10:57:41.528 INFO: Project root configuration file: /Users/daniel/go/src/github.build.ge.com/sonar-project.properties
10:57:41.572 INFO: SonarQube Scanner 3.0.3.778
10:57:41.572 INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
10:57:41.572 INFO: Mac OS X 10.12.5 x86_64
10:57:41.749 DEBUG: keyStore is : 
10:57:41.749 DEBUG: keyStore type is : jks
10:57:41.749 DEBUG: keyStore provider is : 
10:57:41.749 DEBUG: init keystore
10:57:41.750 DEBUG: init keymanager of type SunX509
10:57:41.863 INFO: User cache: /Users/daniel/.sonar/cache
10:57:41.863 DEBUG: Extract sonar-scanner-api-batch in temp...
10:57:41.880 DEBUG: Get bootstrap index...
10:57:41.880 DEBUG: Download: http://localhost:9000/batch/index
10:57:41.935 DEBUG: Get bootstrap completed
10:57:41.935 DEBUG: Create isolated classloader...
10:57:41.951 DEBUG: Start temp cleaning...
10:57:41.971 DEBUG: Temp cleaning done
10:57:41.971 DEBUG: Execution getVersion
10:57:41.975 DEBUG: Execution start
10:57:42.340 DEBUG: Publish global mode
10:57:42.442 INFO: Load global settings
10:57:42.480 DEBUG: GET 200 http://localhost:9000/api/settings/values.protobuf | time=32ms
10:57:42.495 INFO: Load global settings (done) | time=54ms
10:57:42.507 INFO: User cache: /Users/daniel/.sonar/cache
10:57:42.725 INFO: Load plugins index
10:57:42.728 DEBUG: GET 200 http://localhost:9000/deploy/plugins/index.txt | time=3ms
10:57:42.729 INFO: Load plugins index (done) | time=5ms
10:57:42.730 DEBUG: Load plugins
10:57:42.756 DEBUG: Load plugins (done) | time=27ms
10:57:42.768 DEBUG: API compatibility mode is enabled on plugin Git [scmgit] (built with API lower than 5.2)
10:57:42.774 DEBUG: API compatibility mode is enabled on plugin SVN [scmsvn] (built with API lower than 5.2)
10:57:42.877 DEBUG: Plugins:
10:57:42.877 DEBUG:   * C# 5.10.1.1411 (csharp)
10:57:42.877 DEBUG:   * Python 1.7.0.1195 (python)
10:57:42.877 DEBUG:   * SonarJava 4.9.0.9858 (java)
10:57:42.877 DEBUG:   * Flex 2.3 (flex)
10:57:42.877 DEBUG:   * Git 1.2 (scmgit)
10:57:42.877 DEBUG:   * SonarXML 1.4.2.885 (xml)
10:57:42.877 DEBUG:   * Golang 1.2.2 (golang)
10:57:42.877 DEBUG:   * SonarPHP 2.10.0.2087 (php)
10:57:42.877 DEBUG:   * SVN 1.4.0.522 (scmsvn)
10:57:42.878 DEBUG:   * SonarJS 3.0.0.4962 (javascript)
10:57:42.890 DEBUG: Execution getVersion
10:57:42.890 INFO: SonarQube server 6.4.0
10:57:42.890 INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
10:57:42.891 DEBUG: Work directory: /Users/daniel/go/src/github.build.ge.com/.scannerwork
10:57:42.891 DEBUG: Execution getVersion
10:57:42.891 DEBUG: Execution execute
10:57:43.188 INFO: Process project properties
10:57:43.190 DEBUG: Process project properties (done) | time=2ms
10:57:43.279 INFO: Load project repositories
10:57:43.292 DEBUG: GET 200 http://localhost:9000/batch/project.protobuf?key=yourprojectid | time=12ms
10:57:43.345 INFO: Load project repositories (done) | time=66ms
10:57:43.412 DEBUG: Available languages:
10:57:43.412 DEBUG:   * C# => "cs"
10:57:43.412 DEBUG:   * Python => "py"
10:57:43.413 DEBUG:   * Java => "java"
10:57:43.413 DEBUG:   * Flex => "flex"
10:57:43.413 DEBUG:   * XML => "xml"
10:57:43.413 DEBUG:   * GO => "go"
10:57:43.413 DEBUG:   * PHP => "php"
10:57:43.413 DEBUG:   * JavaScript => "js"
10:57:43.415 INFO: Load quality profiles
10:57:43.426 DEBUG: GET 200 http://localhost:9000/api/qualityprofiles/search.protobuf?projectKey=yourprojectid | time=10ms
10:57:43.430 INFO: Load quality profiles (done) | time=15ms
10:57:43.434 INFO: Load active rules
10:57:43.493 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXGdWgHDNxqwPX_s&p=1&ps=500 | time=59ms
10:57:43.624 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXKkWgHDNxqwPYCN&p=1&ps=500 | time=87ms
10:57:43.662 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXPcWgHDNxqwPYGd&p=1&ps=500 | time=24ms
10:57:43.674 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXQfWgHDNxqwPYHa&p=1&ps=500 | time=10ms
10:57:43.691 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXQnWgHDNxqwPYHc&p=1&ps=500 | time=17ms
10:57:43.719 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXVuWgHDNxqwPYMD&p=1&ps=500 | time=26ms
10:57:43.754 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXR9WgHDNxqwPYIo&p=1&ps=500 | time=33ms
10:57:43.774 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AV2alXRXWgHDNxqwPYIF&p=1&ps=500 | time=18ms
10:57:43.783 INFO: Load active rules (done) | time=350ms
10:57:43.784 INFO: Load metrics repository
10:57:43.793 DEBUG: GET 200 http://localhost:9000/api/metrics/search?f=name,description,direction,qualitative,custom&ps=500&p=1 | time=9ms
10:57:43.832 INFO: Load metrics repository (done) | time=48ms
10:57:43.885 WARN: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
10:57:43.885 INFO: Publish mode
10:57:43.885 INFO: Project key: yourprojectid
10:57:43.885 DEBUG: Start recursive analysis of project modules
10:57:43.887 INFO: -------------  Scan name of project
10:57:44.014 INFO: Load server rules
10:57:44.110 DEBUG: GET 200 http://localhost:9000/api/rules/list.protobuf | time=96ms
10:57:44.120 INFO: Load server rules (done) | time=105ms
10:57:44.191 DEBUG: Declared extensions of language C# were converted to sonar.lang.patterns.cs : **/*.cs
10:57:44.191 DEBUG: Declared extensions of language Python were converted to sonar.lang.patterns.py : **/*.py
10:57:44.192 DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
10:57:44.192 DEBUG: Declared extensions of language Flex were converted to sonar.lang.patterns.flex : **/*.as
10:57:44.192 DEBUG: Declared extensions of language XML were converted to sonar.lang.patterns.xml : **/*.xml,**/*.xsd,**/*.xsl
10:57:44.192 DEBUG: Declared extensions of language GO were converted to sonar.lang.patterns.go : **/*.go
10:57:44.192 DEBUG: Declared extensions of language PHP were converted to sonar.lang.patterns.php : **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
10:57:44.192 DEBUG: Declared extensions of language JavaScript were converted to sonar.lang.patterns.js : **/*.js
10:57:44.241 DEBUG: Initializers : GenericCoverageSensor
10:57:44.242 INFO: Initializer GenericCoverageSensor
10:57:44.242 INFO: Initializer GenericCoverageSensor (done) | time=0ms
10:57:44.242 INFO: Base dir: /Users/daniel/go/src/github.build.ge.com
10:57:44.242 INFO: Working dir: /Users/daniel/go/src/github.build.ge.com/.scannerwork
10:57:44.243 INFO: Source paths: .
10:57:44.243 INFO: Source encoding: UTF-8, default locale: en_US
10:57:44.245 INFO: Index files
10:57:44.256 DEBUG: 'sonar-project.properties' indexed with language 'null'
10:57:44.257 DEBUG: 'report.xml' indexed with language 'xml'
10:57:44.258 DEBUG: 'hello.go' indexed with language 'go'
10:57:44.258 INFO: 3 files indexed
10:57:44.259 INFO: Quality profile for go: Golint Rules
10:57:44.259 INFO: Quality profile for xml: Sonar way
10:57:44.883 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
10:57:44.883 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
10:57:44.884 DEBUG: 'C#' skipped because there is no related file in current project
10:57:44.884 DEBUG: 'C# Unit Tests Coverage Report Import' skipped because there is no related file in current project
10:57:44.884 DEBUG: 'C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
10:57:44.884 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
10:57:44.884 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
10:57:44.884 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
10:57:44.885 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
10:57:44.885 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
10:57:44.885 DEBUG: 'Flex' skipped because there is no related file in current project
10:57:44.885 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
10:57:44.886 DEBUG: 'PHP sensor' skipped because there is no related file in current project
10:57:44.886 DEBUG: 'JavaScript Squid Sensor' skipped because there is no related file in current project
10:57:44.888 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
10:57:44.889 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
10:57:44.889 DEBUG: 'C#' skipped because there is no related file in current project
10:57:44.889 DEBUG: 'C# Unit Tests Coverage Report Import' skipped because there is no related file in current project
10:57:44.889 DEBUG: 'C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
10:57:44.889 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
10:57:44.889 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
10:57:44.889 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'Flex' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'PHP sensor' skipped because there is no related file in current project
10:57:44.890 DEBUG: 'JavaScript Squid Sensor' skipped because there is no related file in current project
10:57:44.894 DEBUG: Sensors : SonarJavaXmlFileSensor -> XML Sensor -> GoMetaLinter issues loader sensor -> Go Coverage -> Go test JUnit loader sensor -> Go Highlighter Sensor -> Go Metrics Sensor -> Analyzer for "php.ini" files -> Zero Coverage Sensor -> CPD Block Indexer
10:57:44.894 INFO: Sensor SonarJavaXmlFileSensor [java]
10:57:44.917 INFO: 1 source files to be analyzed
10:57:45.059 INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=165ms
10:57:45.059 INFO: 1/1 source files have been analyzed
10:57:45.059 INFO: Sensor XML Sensor [xml]
10:57:45.071 DEBUG: 'report.xml' generated metadata  with charset 'UTF-8'
10:57:45.073 DEBUG: Count lines in /Users/daniel/go/src/github.build.ge.com/report.xml
10:57:45.209 INFO: Sensor XML Sensor [xml] (done) | time=150ms
10:57:45.209 INFO: Sensor GoMetaLinter issues loader sensor [golang]
10:57:45.216 INFO: Parse the file report.xml //default
10:57:45.216 INFO: Parsing 'GoLint' Analysis Results
10:57:45.216 INFO: Parsing file /Users/daniel/go/src/github.build.ge.com/report.xml /default
10:57:45.219 ERROR: IOException
java.io.FileNotFoundException: /Users/daniel/go/src/github.build.ge.com/report.xml /default (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor$GoLintResultParser.parse(GoLintIssueLoaderSensor.java:226)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor.parseAndSaveResults(GoLintIssueLoaderSensor.java:135)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor.execute(GoLintIssueLoaderSensor.java:120)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

10:57:45.220 ERROR: Unable to parse the provided Golint file
javax.xml.stream.XMLStreamException: java.io.FileNotFoundException: /Users/daniel/go/src/github.build.ge.com/report.xml /default (No such file or directory)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor$GoLintResultParser.parse(GoLintIssueLoaderSensor.java:263)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor.parseAndSaveResults(GoLintIssueLoaderSensor.java:135)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor.execute(GoLintIssueLoaderSensor.java:120)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.FileNotFoundException: /Users/daniel/go/src/github.build.ge.com/report.xml /default (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at fr.univartois.sonargo.core.rules.GoLintIssueLoaderSensor$GoLintResultParser.parse(GoLintIssueLoaderSensor.java:226)
	... 33 common frames omitted

10:57:45.220 INFO: Sensor GoMetaLinter issues loader sensor [golang] (done) | time=11ms
10:57:45.220 INFO: Sensor Go Coverage [golang]
10:57:45.222 INFO: no coverage file in package /Users/daniel/go/src/github.build.ge.com/coverage.xml / default
10:57:45.223 INFO: no coverage file in package /Users/daniel/go/src/github.build.ge.com/.scannerwork/batch-report/coverage.xml / default
10:57:45.224 INFO: Sensor Go Coverage [golang] (done) | time=4ms
10:57:45.224 INFO: Sensor Go test JUnit loader sensor [golang]
10:57:45.224 INFO: no junit report
10:57:45.224 INFO: Sensor Go test JUnit loader sensor [golang] (done) | time=0ms
10:57:45.224 INFO: Sensor Go Highlighter Sensor [golang]
go
10:57:45.226 INFO: Color the file: /Users/daniel/go/src/github.build.ge.com/hello.go
10:57:45.245 INFO: Licensed under the Apache License, Version 2.0 (the "License"); 52
10:57:45.245 INFO: Licensed under the Apache License, Version 2.0 (the "License"); 60
10:57:45.245 DEBUG: index 52 indexEnd 60
10:57:45.247 DEBUG: 'hello.go' generated metadata  with charset 'UTF-8'
10:57:45.247 INFO: Licensed under the Apache License, Version 2.0 (the "License"); -1
10:57:45.247 INFO: Licensed under the Apache License, Version 2.0 (the "License"); 52
10:57:45.248 INFO: distributed under the License is distributed on an "AS IS" BASIS, 51
10:57:45.248 INFO: distributed under the License is distributed on an "AS IS" BASIS, 57
10:57:45.248 DEBUG: index 51 indexEnd 57
10:57:45.248 INFO: distributed under the License is distributed on an "AS IS" BASIS, -1
10:57:45.248 INFO: distributed under the License is distributed on an "AS IS" BASIS, 51
10:57:45.249 INFO: Line number 13 index start: 42 index end: 44
10:57:45.249 INFO: Line number 13 index start: 28 index end: 30
10:57:45.249 INFO: Line number 13 index start: 16 index end: 19
10:57:45.249 INFO: Line number 17 index start: 0 index end: 7
10:57:45.249 INFO: Line number 19 index start: 0 index end: 6
10:57:45.249 INFO: 	"fmt" 1
10:57:45.249 INFO: 	"fmt" 5
10:57:45.249 DEBUG: index 1 indexEnd 5
10:57:45.250 INFO: 	"fmt" -1
10:57:45.250 INFO: 	"fmt" 1
10:57:45.250 INFO: Line number 23 index start: 0 index end: 4
10:57:45.250 INFO: Line number 24 index start: 4 index end: 7
10:57:45.250 INFO: Line number 25 index start: 10 index end: 13
xml
null
10:57:45.256 INFO: Sensor Go Highlighter Sensor [golang] (done) | time=32ms
10:57:45.256 INFO: Sensor Go Metrics Sensor [golang]
10:57:45.259 INFO: Sensor Go Metrics Sensor [golang] (done) | time=2ms
10:57:45.259 INFO: Sensor Analyzer for "php.ini" files [php]
10:57:45.261 INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=2ms
10:57:45.261 INFO: Sensor Zero Coverage Sensor
10:57:45.268 INFO: Sensor Zero Coverage Sensor (done) | time=7ms
10:57:45.269 INFO: Sensor CPD Block Indexer
10:57:45.269 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for go
10:57:45.269 DEBUG: No CpdMapping for language go
10:57:45.269 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for xml
10:57:45.269 DEBUG: No CpdMapping for language xml
10:57:45.269 INFO: Sensor CPD Block Indexer (done) | time=1ms
10:57:45.269 INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
10:57:45.270 INFO: Calculating CPD for 0 files
10:57:45.271 INFO: CPD calculation finished
10:57:45.416 INFO: Analysis report generated in 140ms, dir size=27 KB
10:57:45.438 INFO: Analysis reports compressed in 21ms, zip size=9 KB
10:57:45.438 INFO: Analysis report generated in /Users/daniel/go/src/github.build.ge.com/.scannerwork/batch-report
10:57:45.438 DEBUG: Upload report
10:57:45.616 DEBUG: POST 200 http://localhost:9000/api/ce/submit?projectKey=yourprojectid&projectName=name%20of%20project | time=177ms
10:57:45.619 INFO: Analysis report uploaded in 181ms
10:57:45.619 INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/yourprojectid
10:57:45.619 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
10:57:45.619 INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AV2e8kwNHzCXUhIkwpYx
10:57:45.620 DEBUG: Report metadata written to /Users/daniel/go/src/github.build.ge.com/.scannerwork/report-task.txt
10:57:45.635 DEBUG: Post-jobs : 
10:57:45.641 INFO: Task total time: 2.745 s
10:57:45.641 INFO: ------------------------------------------------------------------------
10:57:45.641 INFO: EXECUTION SUCCESS
10:57:45.641 INFO: ------------------------------------------------------------------------
10:57:45.641 INFO: Total time: 4.173s
10:57:45.717 INFO: Final Memory: 47M/397M
10:57:45.717 INFO: ------------------------------------------------------------------------
10:57:45.718 DEBUG: Execution getVersion
10:57:45.719 DEBUG: Execution stop

### Versions

Versions of your sonar installation (
soanr server 6.4
sonar-scanner 3.0
gometalinter.v1 
go version go1.8.3 darwin/amd64
Mac OSX Serra

### Additional Information

Sample reports may be necessary to reproduce the issue. Please attach if possible reports files (report.xml, coverage.xml, test.xml) corresponding to the feature which is not working as expected.

**Comment by blxdaniel** [comment]
Report.xml: 

<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0"><file name="hello.go"><error column="9" line="24" message="don&#39;t use leading k in Go names; var kNUMBERR should be nUMBERR" severity="warning" source="golint"></error></file></checkstyle>

Hello.go:
package main

import (
	"fmt"
)

func main(){
    var kNUMBERR = 1 
    fmt.Println(kNUMBERR)
}

**Comment by thibaultfalque** [comment]
Hi, 

you run "sonar-scanner" before generate report by gometalinter, it's wrong. 

The correct command is: 
`gometalinter.v1 --checkstyle > report.xml`
`... (launch other tools: for coverage and test, but this step is optional)`
and after 
`sonar-scanner`

**Comment by blxdaniel** [comment]
Hello, 

I have followed those steps and this is the result I get from the UI:
<img width="1210" alt="screen shot 2017-08-01 at 11 40 55 am" src="https://user-images.githubusercontent.com/8649216/28841232-694dc480-76ae-11e7-997d-e6beb603930c.png">

**Comment by thibaultfalque** [comment]
ok I a IOException for the report file. 

`ERROR: IOException
java.io.FileNotFoundException: /Users/daniel/go/src/github.build.ge.com/report.xml /default (No such file or directory)`

Do you have the report in the same path of sonar-project.properties?

**Comment by blxdaniel** [comment]
Yes, the report.xml is in the same dir as the sonar-project.properties file

**Comment by blxdaniel** [comment]
I was able to get it to work! Thank you! The problem was the "//default" in the sonar-project.properties. I believe it read the //default at as path. Once i deleted the comment, it appeared!
